# file: roles/hadoop_cdh5_cl/tasks/repo.yml

- name: install_cdh5_repo
  yum: name=http://archive.cloudera.com/cdh5/one-click-install/redhat/6/x86_64/cloudera-cdh-5-0.x86_64.rpm state=installed
  tags:
    - cdh5
