# ========================
# role-wide parameters
# ========================
cdh5_pseudo_host: 'pseudo'
cdh5_pseudo_data_dir_list:
  - '/data/1'

# =========================================
# parameters for each configuration file
# =========================================

# core-site.xml
cdh5_pseudo_fs_default_name: 'hdfs://{{ cdh5_pseudo_host }}:8020'

# hdfs-site.xml
cdh5_pseudo_dfs_nn_name_dir_list:
  - '/data/1/dfs/nn'
cdh5_pseudo_dfs_name_checkpoint_dir_list:
  - '/data/1/dfs/snn'
cdh5_dfs_dn_data_dir_list:
  - '/data/1/dfs/dn'

# mapred-site.xml
cdh5_pseudo_ganglia_servers: '239.2.11.71:8649'
cdh5_pseudo_mapreduce_map_memory_mb: '1024'
cdh5_pseudo_mapreduce_reduce_memory_mb: '1024'
cdh5_pseudo_mapreduce_am_command_opts: '-Xmx1024m'
cdh5_pseudo_yarn_app_mapreduce_am_resource_mb: '1536'

# yarn-site.xml
cdh5_pseudo_yarn_nodemanager_resource_cpu_vcores: '8'
cdh5_pseudo_yarn_scheduler_minimum_allocation_vcores: '1'
cdh5_pseudo_yarn_scheduler_maximum_allocation_vcores: '8'
cdh5_pseudo_yarn_nodemanager_resource_memory_mb: '8092'
cdh5_pseudo_yarn_scheduler_minimum_allocation_mb: '512'
cdh5_pseudo_yarn_scheduler_maximum_allocation_mb: '8092'
cdh5_pseudo_yarn_nodemanager_vmem_pmem_ratio: '1.2'
cdh5_pseudo_yarn_nodemanager_pmem_check_enabled: 'true'
cdh5_pseudo_yarn_nodemanager_vmem_check_enabled: 'true'
cdh5_pseudo_yarn_nm_remote_app_log_dir: '/var/log/hadoop-yarn/apps'
cdh5_pseudo_yarn_app_mapreduce_am_resource_mb: '1536'
