# This is for CentOS6
common_iptables_state: "stopped"
# This is for CentOS7
common_firewalld_state: "stopped"

common_hosts_replace: False
common_hosts_tmpl: "hosts.default"

common_selinux_state: "disabled"

common_config_hostname: False

common_lang: 'en_US.UTF-8'
