- hosts: hadoop_journalnode
  gather_facts: no
  tasks:
    - name: start_daemons
      service: name={{ item }} state=started
      with_items:
        - hadoop-hdfs-journalnode

- hosts: hadoop_client
  tasks:
    - name: wait_for_journalnode_service_port
      wait_for: host={{ item }} port=8480 timeout={{ cdh5_wait_for_timeout }}
      with_items: groups['hadoop_journalnode']

- hosts: hadoop_namenode
  gather_facts: no
  tasks:
    - name: start_daemons
      service: name={{ item }} state=started
      with_items:
        - hadoop-hdfs-namenode
        - hadoop-hdfs-zkfc

- hosts: hadoop_client
  tasks:
    - name: wait_for_namenode_service_port
      wait_for: host={{ item }} port=8020 timeout={{ cdh5_wait_for_timeout }}
      with_items: groups['hadoop_namenode']

- hosts: hadoop_slave
  gather_facts: no
  tasks:
    - name: start_daemons
      service: name={{ item }} state=started
      with_items:
        - hadoop-hdfs-datanode

- hosts: hadoop_client
  tasks:
    - name: wait_for_datanode_service_port
      wait_for: host={{ item }} port=50020 timeout={{ cdh5_wait_for_timeout }}
      with_items: groups['hadoop_slave']
