- hosts: "{{ server | default('hdoop_client') }}"
  roles:
    - { role: common, common_config_hostname: True }
    - jdk
    - maven
    - alluxio_yarn

- hosts: "{{ server | default('hadoop_slave') }}"
  roles:
    - { role: common, common_config_hostname: True }
    - alluxio_conf
