# file: roles/common/tasks/selinux.yml

- name: install_libselinux-python
  yum: name=libselinux-python state=installed

- name: disable_selinux_config
  selinux: state={{ common_selinux_state }}

- name: check_selinux_state
  shell: getenforce
  register: selinux_state
  ignore_errors: True
  always_run: yes

- name: disable_selinux_with_command
  shell: setenforce 0
  when: selinux_state.stderr.find('Disabled') == False
