- name: stop_warning_about_usage_of_loopback
  lineinfile:
    dest: /etc/sysconfig/docker-storage
    regexp: '^DOCKER_STORAGE_OPTIONS'
    line: 'DOCKER_STORAGE_OPTIONS="--storage-opt dm.no_warn_on_loop_devices=true"'
  when: docker_stop_warn_loopback
  notify: restat_docker
