---
influxdb_hostname: 'localhost'
influxdb_meta_bind_address: ':8089'
influxdb_http_bind_address: ':8086'
influxdb_graphite_enabled: 'true'
influxdb_graphite_templates:
  - 'spark.* measurement.appid.measurement*'

# The following parameters are configured in groups_vars/all/influxdb
influxdb_graphite_db_name: 'graphite'
