# debug mode to print debug messages
ec2_hadoop_debug: False

# Tag name to be attached to instances
ec2_hadoop_instance_tag: hadoop

# Security group ids
#ec2_hadoop_group_id: sg-xxxxxxxx

# The name of private key
#ec2_hadoop_accesskey: xxxxxx

# The type of instances
#ec2_hadoop_master_itype: xx.xxxxx
#ec2_hadoop_slave_itype: xx.xxxxx
#ec2_hadoop_client_itype: xx.xxxxx

# The id of AMI image
#ec2_hadoop_master_image: ami-xxxxxxxx
#ec2_hadoop_slave_image: ami-xxxxxxxx
#ec2_hadoop_client_image: ami-xxxxxxxx

# The id of region
#ec2_hadoop_region: xx-xxxxxxxxx-x

# The id of subnet of VPC
#ec2_hadoop_vpc_subnet_id: subnet-xxxxxxxx

# The placement group
# Notice: The placement group is available for only certain instance types
#ec2_hadoop_placement_group: xxxxxxx

ec2_hadoop_ma_list:
  - name: master01
    ip: 172.31.16.11
  - name: master02
    ip: 172.31.16.12
  - name: master03
    ip: 172.31.16.13

ec2_hadoop_sl_list:
  - name: slave01
    ip: 172.31.16.21
  - name: slave02
    ip: 172.31.16.22
  - name: slave03
    ip: 172.31.16.23
  - name: slave04
    ip: 172.31.16.24
  - name: slave05
    ip: 172.31.16.25

ec2_hadoop_cl_list:
  - name: client01
    ip: 172.31.16.31
