- name: up_masters
  ec2:
    key_name: "{{ ec2_hadoop_accesskey }}"
    instance_type: "{{ ec2_hadoop_master_itype }}"
    group_id: "{{ ec2_hadoop_group_id }}"
    image: "{{ ec2_hadoop_master_image }}"
    wait: yes
    region: "{{ ec2_hadoop_region }}"
    instance_tags:
      name: "{{ ec2_hadoop_instance_tag }}"
      nodetype: "{{ item.name }}"
    exact_count: 1
    count_tag:
      name: "{{ ec2_hadoop_instance_tag }}"
      nodetype: "{{ item.name }}"
    private_ip: "{{ item.ip }}"
    vpc_subnet_id: "{{ ec2_hadoop_vpc_subnet_id }}"
    placement_group: "{{ ec2_hadoop_placement_group }}"
  with_items: ec2_hadoop_ma_list
  register: ec2_hadoop_ma_result

- name: up_slaves
  ec2:
    key_name: "{{ ec2_hadoop_accesskey }}"
    instance_type: "{{ ec2_hadoop_slave_itype }}"
    group_id: "{{ ec2_hadoop_group_id }}"
    image: "{{ ec2_hadoop_slave_image }}"
    wait: yes
    region: "{{ ec2_hadoop_region }}"
    instance_tags:
      name: "{{ ec2_hadoop_instance_tag }}"
      nodetype: "{{ item.name }}"
    exact_count: 1
    count_tag:
      name: "{{ ec2_hadoop_instance_tag }}"
      nodetype: "{{ item.name }}"
    private_ip: "{{ item.ip }}"
    vpc_subnet_id: "{{ ec2_hadoop_vpc_subnet_id }}"
    placement_group: "{{ ec2_hadoop_placement_group }}"
  with_items: ec2_hadoop_sl_list
  register: ec2_hadoop_sl_result

- name: up_client
  ec2:
    key_name: "{{ ec2_hadoop_accesskey }}"
    instance_type: "{{ ec2_hadoop_client_itype }}"
    group_id: "{{ ec2_hadoop_group_id }}"
    image: "{{ ec2_hadoop_client_image }}"
    wait: yes
    region: "{{ ec2_hadoop_region }}"
    instance_tags:
      name: "{{ ec2_hadoop_instance_tag }}"
      nodetype: "{{ item.name }}"
    exact_count: 1
    count_tag:
      name: "{{ ec2_hadoop_instance_tag }}"
      nodetype: "{{ item.name }}"
    private_ip: "{{ item.ip }}"
    vpc_subnet_id: "{{ ec2_hadoop_vpc_subnet_id }}"
    placement_group: "{{ ec2_hadoop_placement_group }}"
  with_items: ec2_hadoop_cl_list
  register: ec2_hadoop_cl_result

- name: print_master_debugs
  debug: var="{{ ec2_hadoop_ma_result.results }}"
  when: ec2_hadoop_debug

- name: print_slave_debugs
  debug: msg="{{ ec2_hadoop_sl_result.results }}"
  when: ec2_hadoop_debug

- name: print_client_debugs
  debug: msg="{{ ec2_hadoop_cl_result.results }}"
  when: ec2_hadoop_debug

- name: make_out_dir
  file: path="/tmp/ec2_{{ ansible_user_id }}_{{ ansible_date_time.epoch }}" state=directory

- name: make_inventory
  local_action: template src=ansible_hosts.j2 dest="/tmp/ec2_{{ ansible_user_id }}_{{ ansible_date_time.epoch }}/ansible_hosts"

- name: make_local_hosts_for_os
  local_action: template src=hosts.j2 dest="/tmp/ec2_{{ ansible_user_id }}_{{ ansible_date_time.epoch }}/hosts"

- name: make_public_hosts_for_os
  local_action: template src=publichosts.j2 dest="/tmp/ec2_{{ ansible_user_id }}_{{ ansible_date_time.epoch }}/publichosts"

- name: make_ip_list
  local_action: template src=ips.j2 dest="/tmp/ec2_{{ ansible_user_id }}_{{ ansible_date_time.epoch }}/ips"
