---
# tasks file for roles/endosnipe_datacollector
- name: mkdir_ENdoSnipe
  file:
    path: /opt/ENdoSnipe
    state: directory
  tags: endo_datacollector

- name: download_endosnipe_zip
  get_url:
    url: http://downloads.sourceforge.net/project/endosnipe/6.0.0-release/endosnipe_6.0.0-release.zip?r=http%3A%2F%2Fwww.endosnipe.com%2Freference%2Findex.html&ts=1472173222&use_mirror=jaist
    dest: /opt/ENdoSnipe/endosnipe_6.0.0-release.zip
  tags: endo_datacollector

- name: unarchive_endosnipe
  unarchive:
    copy: no
    src: /opt/ENdoSnipe/endosnipe_6.0.0-release.zip
    dest: /opt/ENdoSnipe/
  tags: endo_datacollector

- name: unarchive_datacollector
  unarchive:
    copy: no
    src: /opt/ENdoSnipe/endosnipe_6.0.0-release/endosnipe-datacollector-6.0.0.tar.gz
    dest: /opt/
  tags: endo_datacollector

- name: copy_collector.properties
  template:
    src: collector.properties.j2
    dest: /opt/ENdoSnipe/DataCollector/conf/collector.properties
  tags: endo_datacollector
